namespace LiteHttp.Extensions;

public static class ResponseCodeExtensions
{
    public static ReadOnlyMemory<byte> AsByteString(this ResponseCode responseCode) => responseCode switch
    {
        ResponseCode.Continue => ResponseCodesAsBytes.Continue,
        ResponseCode.SwitchingProtocols => ResponseCodesAsBytes.SwitchingProtocols,
        ResponseCode.Processing => ResponseCodesAsBytes.Processing,
        ResponseCode.EarlyHints => ResponseCodesAsBytes.EarlyHints,
        ResponseCode.Ok => ResponseCodesAsBytes.Ok,
        ResponseCode.Created => ResponseCodesAsBytes.Created,
        ResponseCode.Accepted => ResponseCodesAsBytes.Accepted,
        ResponseCode.NoContent => ResponseCodesAsBytes.NoContent,
        ResponseCode.ResetContent => ResponseCodesAsBytes.ResetContent,
        ResponseCode.PartialContent => ResponseCodesAsBytes.PartialContent,
        ResponseCode.MultiStatus => ResponseCodesAsBytes.MultiStatus,
        ResponseCode.AlreadyReported => ResponseCodesAsBytes.AlreadyReported,
        ResponseCode.ImUsed => ResponseCodesAsBytes.ImUsed,
        ResponseCode.MultipleChoices => ResponseCodesAsBytes.MultipleChoices,
        ResponseCode.MovedPermanently => ResponseCodesAsBytes.MovedPermanently,
        ResponseCode.Found => ResponseCodesAsBytes.Found,
        ResponseCode.SeeOther => ResponseCodesAsBytes.SeeOther,
        ResponseCode.NotModified => ResponseCodesAsBytes.NotModified,
        ResponseCode.UseProxy => ResponseCodesAsBytes.UseProxy,
        ResponseCode.SwitchProxy => ResponseCodesAsBytes.SwitchProxy,
        ResponseCode.TemporaryRedirect => ResponseCodesAsBytes.TemporaryRedirect,
        ResponseCode.PermanentRedirect => ResponseCodesAsBytes.PermanentRedirect,
        ResponseCode.BadRequest => ResponseCodesAsBytes.BadRequest,
        ResponseCode.Unauthorized => ResponseCodesAsBytes.Unauthorized,
        ResponseCode.PaymentRequired => ResponseCodesAsBytes.PaymentRequired,
        ResponseCode.Forbidden => ResponseCodesAsBytes.Forbidden,
        ResponseCode.NotFound => ResponseCodesAsBytes.NotFound,
        ResponseCode.MethodNotAllowed => ResponseCodesAsBytes.MethodNotAllowed,
        ResponseCode.NotAcceptable => ResponseCodesAsBytes.NotAcceptable,
        ResponseCode.ProxyAuthenticationRequired => ResponseCodesAsBytes.ProxyAuthenticationRequired,
        ResponseCode.RequestTimeout => ResponseCodesAsBytes.RequestTimeout,
        ResponseCode.Conflict => ResponseCodesAsBytes.Conflict,
        ResponseCode.Gone => ResponseCodesAsBytes.Gone,
        ResponseCode.LengthRequired => ResponseCodesAsBytes.LengthRequired,
        ResponseCode.PreconditionFailed => ResponseCodesAsBytes.PreconditionFailed,
        ResponseCode.ContentTooLarge => ResponseCodesAsBytes.ContentTooLarge,
        ResponseCode.UriTooLong => ResponseCodesAsBytes.UriTooLong,
        ResponseCode.UnsupportedMediaType => ResponseCodesAsBytes.UnsupportedMediaType,
        ResponseCode.RangeNotSatisfiable => ResponseCodesAsBytes.RangeNotSatisfiable,
        ResponseCode.ExpectationFailed => ResponseCodesAsBytes.ExpectationFailed,
        ResponseCode.ImATeapot => ResponseCodesAsBytes.ImATeapot,
        ResponseCode.MisdirectedRequest => ResponseCodesAsBytes.MisdirectedRequest,
        ResponseCode.UnprocessableEntity => ResponseCodesAsBytes.UnprocessableEntity,
        ResponseCode.Locked => ResponseCodesAsBytes.Locked,
        ResponseCode.FailedDependency => ResponseCodesAsBytes.FailedDependency,
        ResponseCode.TooEarly => ResponseCodesAsBytes.TooEarly,
        ResponseCode.UpgradeRequired => ResponseCodesAsBytes.UpgradeRequired,
        ResponseCode.PreconditionRequired => ResponseCodesAsBytes.PreconditionRequired,
        ResponseCode.TooManyRequests => ResponseCodesAsBytes.TooManyRequests,
        ResponseCode.RequestHeaderFieldsTooLarge => ResponseCodesAsBytes.RequestHeaderFieldsTooLarge,
        ResponseCode.UnavailableForLegalReasons => ResponseCodesAsBytes.UnavailableForLegalReasons,
        ResponseCode.InternalServerError => ResponseCodesAsBytes.InternalServerError,
        ResponseCode.NotImplemented => ResponseCodesAsBytes.NotImplemented,
        ResponseCode.BadGateway => ResponseCodesAsBytes.BadGateway,
        ResponseCode.ServiceUnavailable => ResponseCodesAsBytes.ServiceUnavailable,
        ResponseCode.GatewayTimeout => ResponseCodesAsBytes.GatewayTimeout,
        ResponseCode.HttpVersionNotSupported => ResponseCodesAsBytes.HttpVersionNotSupported,
        ResponseCode.VariantAlsoNegotiates => ResponseCodesAsBytes.VariantAlsoNegotiates,
        ResponseCode.InsufficientStorage => ResponseCodesAsBytes.InsufficientStorage,
        ResponseCode.LoopDetected => ResponseCodesAsBytes.LoopDetected,
        ResponseCode.NotExtended => ResponseCodesAsBytes.NotExtended,
        ResponseCode.NetworkAuthenticationRequired => ResponseCodesAsBytes.NetworkAuthenticationRequired,
        _ => throw new FormatException("Unknown response code")
    };
}