global using System.Net;
global using System.Net.Sockets;
global using System.Text;
global using LiteHttp.Enums;
global using LiteHttp.Models;
global using LiteHttp.Constants;
global using LiteHttp.Extensions;
global using LiteHttp.Abstractions;
global using LiteHttp.Models.Events;
global using System.Numerics